version: '3'
services:
  pyweb:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"