version: '3'
services:
  pyweb:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
#    volumes:
#      - ./app:/app  # Монтируем локальную директорию с приложением внутрь контейнера
#    working_dir: /app
#    command: python app.py  # Команда для запуска вашего приложения